apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: api.newrelic.com
spec:
  hosts:
    - infra-api.newrelic.com
    - identity-api.newrelic.com
    - infrastructure-command-api.newrelic.com
  ports:
    - number: 443
      name: https
      protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL